package com.xinzhili.doctor.database.sqlite.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xinzhili.doctor.database.sqlite.entity.DoctorBean;

import com.xinzhili.doctor.database.sqlite.greendao.DoctorBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doctorBeanDaoConfig;

    private final DoctorBeanDao doctorBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doctorBeanDaoConfig = daoConfigMap.get(DoctorBeanDao.class).clone();
        doctorBeanDaoConfig.initIdentityScope(type);

        doctorBeanDao = new DoctorBeanDao(doctorBeanDaoConfig, this);

        registerDao(DoctorBean.class, doctorBeanDao);
    }
    
    public void clear() {
        doctorBeanDaoConfig.clearIdentityScope();
    }

    public DoctorBeanDao getDoctorBeanDao() {
        return doctorBeanDao;
    }

}
